# Welcome to Jekyll!

# Website settings
title: Kang-Hua
description: My CV at https://kanghuawu.github.io/
keywords: kang-hua,wu,cv,resume
baseurl: https://kanghuawu.github.io/CV/
url: https://kanghuawu.github.io/CV/
# url: http://127.0.0.1:4000

# baidu analytics
# ba:
#   uuid: 317acca9ef9255b934e46371e471431d

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
